//Token EAAGKdyadfZCgBAKsZA2XVH2qLOeS3O1ZAeZAlZCoCHiMOQoLQwUa6H0Y0lUlKQQrIhaBLk3lr6zm8MSc675ZAZAYLJaSNUlSZBfVpf9alOnBIoGZASzuTU89coZBQIv9EE6Hbj1ykUeGrnsQzJTxlov9ZBiA3iwZB5ZAbIS9YGUNRsYZClul8A6OSWb4vSI7qSTMCqTn8ZD
CREATE DATABASE BEMDAORA;
USE BEMDAORA;

CREATE TABLE `BEMDAORA`.`ACESSO` (`ID` bigint NOT NULL AUTO_INCREMENT, `DT_FIM` datetime NOT NULL, `DT_INICIO` datetime, `IP` varchar(16) NOT NULL, `STATUS` varchar(30) NOT NULL, `TICKET` varchar(255) NOT NULL, `ID_USUARIO` bigint, `PERMANENTE` int(1) NOT NULL, PRIMARY KEY (`ID`, `TICKET`), INDEX `ACESSO_USUARIO` (`ID_USUARIO`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `BEMDAORA`.`USUARIO` (`ID` bigint NOT NULL AUTO_INCREMENT, `NOME` varchar(255) NOT NULL, `EMAIL` varchar(255) NOT NULL, `SENHA` varchar(255) NOT NULL, `IDADE` int(3) NOT NULL, PRIMARY KEY (`ID`), INDEX `IND_USUARIO_NOME` (`NOME`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE `BEMDAORA`.`ACESSO` ADD CONSTRAINT `ACESSO_USUARIO` FOREIGN KEY (`ID_USUARIO`) REFERENCES `BEMDAORA`.`USUARIO` (`ID`);



select * from USUARIO ORDER BY ID DESC;
select * from INSTITUICAO ORDER BY ID DESC;
select * from VOLUNTARIO;

select * from VAGA;

select * from ACESSO;

select * from LOCK_LOGIN;

SELECT * FROM RAMO_ATIVIDADE;



select * from FOTO_INSTITUICAO;




