CREATE DATABASE BEMDAORA;
USE BEMDAORA;

CREATE TABLE `BEMDAORA`.`ACESSO` (`ID` bigint NOT NULL AUTO_INCREMENT, `DT_FIM` datetime NOT NULL, `DT_INICIO` datetime, `IP` varchar(16) NOT NULL, `STATUS` varchar(30) NOT NULL, `TICKET` varchar(255) NOT NULL, `ID_USUARIO` bigint, `PERMANENTE` int(1) NOT NULL, PRIMARY KEY (`ID`, `TICKET`), INDEX `ACESSO_USUARIO` (`ID_USUARIO`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `BEMDAORA`.`USUARIO` (`ID` bigint NOT NULL AUTO_INCREMENT, `NOME` varchar(255) NOT NULL, `EMAIL` varchar(255) NOT NULL, `SENHA` varchar(255) NOT NULL, `IDADE` int(3) NOT NULL, PRIMARY KEY (`ID`), INDEX `IND_USUARIO_NOME` (`NOME`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE `BEMDAORA`.`ACESSO` ADD CONSTRAINT `ACESSO_USUARIO` FOREIGN KEY (`ID_USUARIO`) REFERENCES `BEMDAORA`.`USUARIO` (`ID`);



select * from USUARIO ORDER BY ID DESC;
select * from INSTITUICAO ORDER BY ID DESC;
select * from VOLUNTARIO;


